Controllers/InformeVertederosController.cs
using SGS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGS.Controllers
{
    public class InformeVertederosController : Controller
    {
        //
        // GET: /InformeVertederos/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult buscar(String desde, String hasta)
        {
            DateTime inicio = Convert.ToDateTime(desde);
            DateTime fin = Convert.ToDateTime(hasta);
            sgsbdEntities db = new sgsbdEntities();
            List<Models.SP_SEL_informe_vertederos_Result> lstListaVertederos = db.SP_SEL_informe_vertederos(inicio, fin, Models.repository.UsuariosRepository.getUnidadSeleccionada()).ToList();

            return View("result", lstListaVertederos);
        }


        public ActionResult excel(String desde, String hasta)
        {
            DateTime inicio = Convert.ToDateTime(desde);
            DateTime fin = Convert.ToDateTime(hasta);
            sgsbdEntities db = new sgsbdEntities();
            List<Models.SP_SEL_informe_vertederos_Result> lstListaVertederos = db.SP_SEL_informe_vertederos(inicio, fin, Models.repository.UsuariosRepository.getUnidadSeleccionada()).ToList();

            ViewBag.desde = desde;
            ViewBag.hasta = hasta;

            return View(lstListaVertederos);

        }

    }
}

Views/InformeVertederos/excel.cshtml
@{
    Layout = null;
    Response.AddHeader("Content-type", "application/vnd.ms-excel");
    Response.AddHeader("Content-Disposition", "attachment; filename=Informe_Vertedero.xls");
}

<table border="0">
    <thead>
        <tr>
            <th colspan="14">
                <h2>Informe de Vertederos</h2>
            </th>
        </tr>
        <tr>
            <th>
                Fecha desde:
            </th>
            <th>
                @ViewBag.desde
            </th>
            <th>
                Fecha Hasta:
            </th>
            <th>
                @ViewBag.hasta
            </th>
        </tr>
    </thead>
</table>
<br />
<table border="1">
    <thead>
        <tr>


            <th style="background-color: #cccccc">Fecha</th>
            <th style="background-color: #cccccc">Rut</th>
            <th style="background-color: #cccccc">Razon Social</th>
            <th style="background-color: #cccccc">Servicio</th>
            <th style="background-color: #cccccc">m3</th>
            <th style="background-color: #cccccc">Nro Guia</th>
            <th style="background-color: #cccccc">Patente Camion</th>
            <th style="background-color: #cccccc">Chofer</th>
            <th style="background-color: #cccccc">Industria</th>
            <th style="background-color: #cccccc">Tipo Residuo</th>
            <th style="background-color: #cccccc">Vertedero</th>
    
        </tr>
    </thead>
    <tbody>
        @foreach (var m in Model)
        {
            <tr>
                <td>@Convert.ToDateTime(m.fecha).ToString("dd-MM-yyyy")</td>
                <td>@m.rut</td>
                <td>@m.razonsocial</td>
                <td>@m.servicio</td>
                <td>@m.m3</td>
                <td>@Convert.ToInt32(m.nro_guia).ToString()</td>
                <td>@m.patente</td>
                <td>@m.chofer</td>
                <td>@m.industria</td>
                <td>@m.tipo_residuo</td>
                <td>@m.vertedero</td>
            </tr>

        }
    </tbody>
</table>

Views/InformeVertederos/index.cshtml
@*
    
    
    Descripción: contenedor principal de Informe de Vertederos
*@
@{
    string token = Guid.NewGuid().ToString();
}
@{
    ViewBag.Title = "index";
    Layout = "~/Views/Shared/_main_layout.cshtml";
}

@section scripts {
    <script src="@Url.Content("~/Scripts/jquery.datatable1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/dataTables.bootstrap.min.js")"></script>
    <script type="text/javascript">
        $(function () {
            var vista = $("#@token");

            $('.datepicker').datepicker();

            var paginar = (function () {
                vista.find('.datatable').dataTable({
                    "sDom": "<'row'<'col-lg-6'l><'col-lg-6'f>r>t<'row'<'col-lg-12'i><'col-lg-12 center'p>>",
                    "sPaginationType": "bootstrap",
                    "oLanguage": {
                        "sLengthMenu": "_MENU_ Registros por pagina"
                    }
                });
            });

            paginar();

            vista.find('button[data-action="Buscar"]:first').click(function () {
                var desde = vista.find('#fechaDesde');
                var hasta = vista.find('#fechaHasta');
                if (Fwk.Validation.Validate('Ingreso')) {
                    $page.loading_all.show("Buscando...");
                    var btn = $(this);
                    btn.button('loading');
                    $page.ajax({
                        url: "@Url.Action("buscar", "InformeVertederos")" + "?desde=" + desde.val() + "&hasta=" + hasta.val(),
                        datatype: 'html',
                        success: function (data) {
                            vista.find('div.box-content').html(data);
                            paginar();
                            var aExportar = vista.find('a[data-action="exportar"]:first');
                            aExportar.prop("href", "@Url.Action("excel", "InformeVertederos")" + "?desde=" + desde.val() + "&hasta=" + hasta.val());
                            aExportar.removeClass('hidden');
                            $page.loading_all.hide();
                            btn.button('reset');
                        }
                    });
                }
            });

        });
    </script>

}

<div id="content" class="col-lg-12 col-sm-11  ">
    <div id="@token">
        <div class="row">
            <div class="col-lg-12 col-md-9">
                @Html.Partial("~/Views/Shared/_breadcrumbs.cshtml",
                      new Dictionary<string, string>() {
                            {"Informe de Vertederos",Url.RouteUrl(new {Controller="InformeVertederos",Action="index"})}
                            })
                <div style="margin-bottom: 13px;">
                    <div class="input-group date col-sm-4" style="width:200px;">
                        <span class="input-group-addon"><i class="icon-calendar"></i></span>
                        <input id="fechaDesde" type="text" data-date-format="dd/mm/yyyy" class="form-control datepicker" style="width:140px;" placeholder="Fecha Desde"
                               data-val-rules="required" data-val-for="self" data-val-group="Ingreso">
                    </div>
                    <div class="input-group date col-sm-4" style="width:200px;">
                        <span class="input-group-addon"><i class="icon-calendar"></i></span>
                        <input id="fechaHasta" type="text" data-date-format="dd/mm/yyyy" class="form-control datepicker" style="width:140px;" placeholder="Fecha Hasta"
                               data-val-rules="required" data-val-for="self" data-val-group="Ingreso">
                    </div>
                    <button type="button" data-loading-text="Buscando..." class="btn btn-success btn-lg" data-action="Buscar">Buscar</button>
                </div>

                <div class="box">
                    <div class="box-header" data-original-title>
                        <h2><i class="icon-folder-close"></i><span class="break"></span>Informe de Vertederos</h2>
                        <a class="btn btn-lg pull-right btn-success hidden" data-action="exportar" href="@Url.RouteUrl(new { Controller = "InformeVertederos", action = "Excel" })">Excel</a>
                    </div>
                    <div class="box-content">
                    </div>
                </div>
            </div><!--/col-->

        </div><!--/row-->
    </div>
</div>

Views/InformeVertederos/result.cshtml
@*

    Descripción: lista el informe de vertederos.
*@
@model List<SGS.Models.SP_SEL_informe_vertederos_Result>

@if (Model.Count > 0)
{
    <div style="margin-left:10px;margin-right:10px;">
        @*<h3 style="font-weight: bold;">Historial de Reajustes.</h3>*@

        <table class="table table-striped table-bordered bootstrap-datatable datatable w100" style="font-size:12px">
            <thead role="row" class="tab-header">
                <tr>
                    <th class="sorting_asc" role="columnheader">Fecha Ingreso</th>
                    <th class="sorting">Rut</th>
                    <th class="sorting">Razon Social</th>
                    <th class="sorting">Servicio</th>
                    <th class="sorting">m3</th>
                    <th class="sorting">N° Guia</th>
                    <th class="sorting">Patente Camion</th>
                    <th class="sorting">Chofer</th>
                    <th class="sorting">Industria</th>
                    <th class="sorting">Tipo Residuo</th>
                    <th class="sorting">Vertedero</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var m in Model)
                {
                    <tr>
                        <td>@Convert.ToDateTime(m.fecha).ToString("dd-MM-yyyy")</td>
                        <td>@m.rut</td>
                        <td>@m.razonsocial</td>
                        <td>@m.servicio</td>
                        <td>@m.m3</td>
                        <td>@Convert.ToInt32(m.nro_guia).ToString()</td>
                        <td>@m.patente</td>
                        <td>@m.chofer</td>
                        <td>@m.industria</td>
                        <td>@m.tipo_residuo</td>
                        <td>@m.vertedero</td>
                    
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <text>No se encontraron resultados</text>
}